grains = rbind(
    c("Activated B cells",            "B cells",           "too unspecific"),
    c("Activated T cells",            "too unspecific",        "too unspecific"),
    c("Basophils",                    "others",            "others"),
    c("B cells",                      "B cells",           "too unspecific"),
    c("CD4 T cells",                  "CD4 T cells",       "too unspecific"),
    c("CD8 T cells",                  "CD8 T cells",       "too unspecific"),
    c("Central Memory",               "too unspecific",        "too unspecific"),
    c("Central Memory CD4 T cells",   "CD4 T cells",       "memory CD4 T cells"),
    c("Central Memory CD8 T cells",   "CD8 T cells",       "memory CD8 T cells"),
    c("Central Memory T cells",       "too unspecific",        "too unspecific"),
    c("Dendritic cells",              "monocytic lineage", "myeloid dendritic cells"),
    c("Effector CD4 T cells",         "CD4 T cells",       "too unspecific"),
    c("Effector Memory",              "too unspecific",        "too unspecific"),
    c("Effector Memory CD8 T cells",  "CD8 T cells",       "regulatory T cells"),
    c("Effector Memory T cells",      "too unspecific",        "too unspecific"),
    c("endothelial",                  "endothelial cells", "endothelial cells"),
    c("Eosinophils",                  "others",            "others"),
    c("fibroblast",                   "fibroblasts",       "fibroblasts"),
    c("Follicular helper T cells",    "CD4 T cells",       "too unspecific"),
    c("gamma delta T cells",          "others",            "others"),
    c("GC B cells",                   "B cells",           "too unspecific"),
    c("Granulocytes",                 "neutrophils",       "neutrophils"),
    c("Macrophage",                   "monocytic lineage", "macrophages"),
    c("Memory B cells",               "B cells",           "memory B cells"),
    c("Memory CD4 T cells",           "CD4 T cells",       "memory CD4 T cells"),
    c("Memory CD8 T cells",           "CD8 T cells",       "memory CD8 T cells"),
    c("Memory T cells",               "too unspecific",        "too unspecific"),
    c("Monocytes",                    "monocytic lineage", "monocytes"),
    c("Myeloid Dendritic cells",      "monocytic lineage", "myeloid dendritic cells"),
    c("Naive B cells",                "B cells",           "naive B cells"),
    c("Naive CD4 T cells",            "CD4 T cells",       "naive CD4 T cells"),
    c("Naive CD8 T cells",            "CD8 T cells",       "naive CD8 T cells"),
    c("Naive T cells",                "too unspecific",        "too unspecific"),
    c("Naive T effector cells",       "too unspecific",        "too unspecific"),
    c("Neutrophils",                  "neutrophils",       "neutrophils"),
    c("NK cells",                     "NK cells",          "NK cells"),
    c("NKT cells",                    "others",            "others"),
    c("PBMC",                         "too unspecific",        "too unspecific"),
    c("Plasma cells",                 "B cells",           "others"),
    c("Plasmablast",                  "B cells",           "others"),
    c("Plasmacytoid Dendritic Cells", "others",            "others"),
    c("T cells",                      "too unspecific",        "too unspecific"),
    c("Th1 cells",                    "CD4 T cells",       "others"),
    c("Th2 cells",                    "CD4 T cells",       "others"),
    c("Th17 cells",                   "CD4 T cells",       "others"),
    c("Tregs",                        "CD4 T cells",       "regulatory T cells"),
    c("White blood cells",            "others",            "too unspecific"))

colnames(grains) = c("original", "coarse", "fine")
grains = data.frame(grains)
grains$combined = paste0(grains$fine, "-", grains$coarse)
